from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UsuariosPage(object):
    def setupUi(self, UsuariosPage):
        UsuariosPage.setObjectName("UsuariosPage")
        UsuariosPage.resize(758, 529)
        self.verticalLayout = QtWidgets.QVBoxLayout(UsuariosPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(UsuariosPage)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/img/icons/Nusers.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        
        # BOTÓN REGRESAR
        self.btnRegresar = QtWidgets.QPushButton(self.widget)
        self.btnRegresar.setMinimumSize(QtCore.QSize(100, 40))
        self.btnRegresar.setObjectName("btnRegresar")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/img/icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRegresar.setIcon(icon)
        self.horizontalLayout.addWidget(self.btnRegresar)
        
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(UsuariosPage)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setMinimumSize(QtCore.QSize(15, 15))
        self.label_5.setMaximumSize(QtCore.QSize(15, 15))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/img/icons/search.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.btnAgregar = QtWidgets.QPushButton(self.widget_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/img/icons/agregar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAgregar.setIcon(icon1)
        self.btnAgregar.setIconSize(QtCore.QSize(20, 20))
        self.btnAgregar.setCheckable(True)
        self.btnAgregar.setAutoExclusive(True)
        self.btnAgregar.setObjectName("btnAgregar")
        self.horizontalLayout_2.addWidget(self.btnAgregar)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(UsuariosPage)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.widget_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)  # Cambiado a 6 columnas (5 datos + opciones)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(60)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_3)

        self.retranslateUi(UsuariosPage)
        QtCore.QMetaObject.connectSlotsByName(UsuariosPage)

    def retranslateUi(self, UsuariosPage):
        _translate = QtCore.QCoreApplication.translate
        UsuariosPage.setWindowTitle(_translate("UsuariosPage", "SDLG - Gestión de Usuarios"))
        self.label.setText(_translate("UsuariosPage", "Usuarios"))
        self.btnRegresar.setText(_translate("UsuariosPage", "Regresar"))
        self.label_3.setText(_translate("UsuariosPage", "Buscar"))
        self.btnAgregar.setText(_translate("UsuariosPage", "Agregar"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("UsuariosPage", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("UsuariosPage", "Usuario"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("UsuariosPage", "Nombre"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("UsuariosPage", "Teléfono"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("UsuariosPage", "Rol"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("UsuariosPage", "Opciones"))