# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\bitacora_simple.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BitacoraPage(object):
    def setupUi(self, widget_4):
        widget_4.setObjectName("widget_4")
        widget_4.resize(758, 529)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(widget_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        
        # Header con icono y título
        self.widget = QtWidgets.QWidget(widget_4)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/img/icons/Nbitacora.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(570, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.widget)
        
        # Instrucción
        self.widget_6 = QtWidgets.QWidget(widget_4)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget_6)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout_3.addWidget(self.widget_6)
        
        # Fechas - SIMPLIFICADO
        self.widget_7 = QtWidgets.QWidget(widget_4)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        # Desde
        self.widget_2 = QtWidgets.QWidget(self.widget_7)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.dateEdit_desde = QtWidgets.QDateEdit(self.widget_2)
        self.dateEdit_desde.setCalendarPopup(True)
        self.dateEdit_desde.setObjectName("dateEdit_desde")
        self.verticalLayout.addWidget(self.dateEdit_desde)
        self.horizontalLayout_2.addWidget(self.widget_2)
        
        # Hasta
        self.widget_5 = QtWidgets.QWidget(self.widget_7)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.dateEdit_hasta = QtWidgets.QDateEdit(self.widget_5)
        self.dateEdit_hasta.setCalendarPopup(True)
        self.dateEdit_hasta.setObjectName("dateEdit_hasta")
        self.verticalLayout_2.addWidget(self.dateEdit_hasta)
        self.horizontalLayout_2.addWidget(self.widget_5)
        
        self.verticalLayout_3.addWidget(self.widget_7)
        
        # Espacio
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        
        # Botón
        self.widget_8 = QtWidgets.QWidget(widget_4)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(627, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_generar = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_generar.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_generar.setFont(font)
        self.pushButton_generar.setObjectName("pushButton_generar")
        self.horizontalLayout_3.addWidget(self.pushButton_generar)
        self.verticalLayout_3.addWidget(self.widget_8)

        self.retranslateUi(widget_4)
        QtCore.QMetaObject.connectSlotsByName(widget_4)

    def retranslateUi(self, widget_4):
        _translate = QtCore.QCoreApplication.translate
        widget_4.setWindowTitle(_translate("widget_4", "SDLG - Bitácora"))
        self.label.setText(_translate("widget_4", "Bitácora"))
        self.label_5.setText(_translate("widget_4", "Seleccione un rango de fechas para generar su reporte de bitácora."))
        self.label_3.setText(_translate("widget_4", "Desde"))
        self.label_4.setText(_translate("widget_4", "Hasta"))
        self.pushButton_generar.setText(_translate("widget_4", "Generar Reporte"))
import resources_rc