# ui/index_ui.py
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IndexPage(object):
    def setupUi(self, IndexPage):
        IndexPage.setObjectName("IndexPage")
        IndexPage.resize(758, 529)
        self.gridLayout_3 = QtWidgets.QGridLayout(IndexPage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(IndexPage)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(216, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(217, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.gridLayout.addWidget(self.widget_2, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(217, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 1, 1, 1, 1)
        self.widget_9 = QtWidgets.QWidget(IndexPage)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_5 = QtWidgets.QWidget(self.widget_9)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_7 = QtWidgets.QWidget(self.widget_5)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget_7)
        self.label_5.setMinimumSize(QtCore.QSize(30, 30))
        self.label_5.setMaximumSize(QtCore.QSize(30, 30))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/img/icons/Gcow.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget_7)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_2.addWidget(self.widget_7)
        spacerItem5 = QtWidgets.QSpacerItem(195, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.widget_6 = QtWidgets.QWidget(self.widget_5)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.widget_6)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.horizontalLayout_2.addWidget(self.widget_6)
        self.verticalLayout_7.addWidget(self.widget_5)
        self.widget_18 = QtWidgets.QWidget(self.widget_9)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_8 = QtWidgets.QWidget(self.widget_18)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_10 = QtWidgets.QWidget(self.widget_8)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.widget_10)
        self.label_8.setMinimumSize(QtCore.QSize(20, 20))
        self.label_8.setMaximumSize(QtCore.QSize(20, 20))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/icons/img/icons/mars.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget_10)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.horizontalLayout_3.addWidget(self.widget_10)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.widget_11 = QtWidgets.QWidget(self.widget_8)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.widget_11)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.horizontalLayout_3.addWidget(self.widget_11)
        self.horizontalLayout_9.addWidget(self.widget_8)
        spacerItem7 = QtWidgets.QSpacerItem(159, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_7.addWidget(self.widget_18)
        self.widget_19 = QtWidgets.QWidget(self.widget_9)
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_12 = QtWidgets.QWidget(self.widget_19)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget_13 = QtWidgets.QWidget(self.widget_12)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.widget_13)
        self.label_11.setMinimumSize(QtCore.QSize(20, 20))
        self.label_11.setMaximumSize(QtCore.QSize(20, 20))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/icons/img/icons/venus.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.widget_13)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.horizontalLayout_5.addWidget(self.widget_13)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.widget_14 = QtWidgets.QWidget(self.widget_12)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.widget_14)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.horizontalLayout_5.addWidget(self.widget_14)
        self.horizontalLayout_10.addWidget(self.widget_12)
        spacerItem9 = QtWidgets.QSpacerItem(159, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.verticalLayout_7.addWidget(self.widget_19)
        self.widget_20 = QtWidgets.QWidget(self.widget_9)
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget_15 = QtWidgets.QWidget(self.widget_20)
        self.widget_15.setObjectName("widget_15")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_16 = QtWidgets.QWidget(self.widget_15)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.widget_16)
        self.label_14.setMinimumSize(QtCore.QSize(20, 20))
        self.label_14.setMaximumSize(QtCore.QSize(20, 20))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/icons/img/icons/Gbecerro.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.widget_16)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.horizontalLayout_7.addWidget(self.widget_16)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.widget_17 = QtWidgets.QWidget(self.widget_15)
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtWidgets.QLabel(self.widget_17)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.horizontalLayout_7.addWidget(self.widget_17)
        self.horizontalLayout_11.addWidget(self.widget_15)
        spacerItem11 = QtWidgets.QSpacerItem(159, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.verticalLayout_7.addWidget(self.widget_20)
        self.gridLayout_3.addWidget(self.widget_9, 2, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(IndexPage)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem12 = QtWidgets.QSpacerItem(20, 57, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem12, 0, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(89, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 1, 0, 1, 1)
        self.widget_22 = QtWidgets.QWidget(self.widget_3)
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.widget_22)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem14)
        self.widget_21 = QtWidgets.QWidget(self.widget_22)
        self.widget_21.setObjectName("widget_21")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_21)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton = QtWidgets.QPushButton(self.widget_21)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/img/icons/Bcow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_8.addWidget(self.pushButton)
        spacerItem15 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem15)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_21)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/img/icons/Bbecerro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_8.addWidget(self.pushButton_2)
        spacerItem16 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem16)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_21)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/img/icons/Bfence.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_8.addWidget(self.pushButton_3)
        self.verticalLayout_9.addWidget(self.widget_21)
        self.gridLayout_2.addWidget(self.widget_22, 1, 1, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(89, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem17, 1, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 57, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem18, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.widget_3, 2, 1, 1, 1)

        self.retranslateUi(IndexPage)
        QtCore.QMetaObject.connectSlotsByName(IndexPage)

    def retranslateUi(self, IndexPage):
        _translate = QtCore.QCoreApplication.translate
        IndexPage.setWindowTitle(_translate("IndexPage", "SDLG - Animales"))
        self.label.setText(_translate("IndexPage", "SDLG"))
        self.label_2.setText(_translate("IndexPage", "Software de los Ganaderos"))
        self.label_3.setText(_translate("IndexPage", "para la Ganadería el Colibrí"))
        self.label_6.setText(_translate("IndexPage", "Total de Ganado"))
        self.label_7.setText(_translate("IndexPage", "0"))
        self.label_9.setText(_translate("IndexPage", "Machos"))
        self.label_10.setText(_translate("IndexPage", "0"))
        self.label_12.setText(_translate("IndexPage", "Hembras"))
        self.label_13.setText(_translate("IndexPage", "0"))
        self.label_15.setText(_translate("IndexPage", "Becerros"))
        self.label_16.setText(_translate("IndexPage", "0"))
        self.label_4.setText(_translate("IndexPage", "Acciones rápidas de Ganado"))
        self.pushButton.setText(_translate("IndexPage", "Animales"))
        self.pushButton_2.setText(_translate("IndexPage", "Becerros"))
        self.pushButton_3.setText(_translate("IndexPage", "Corrales"))